"""update_users_schema_and_create_tables

Revision ID: 20aa857c2b5e
Revises: 001_initial_schema
Create Date: 2025-10-16 14:39:08.098909

"""


# revision identifiers, used by Alembic.
revision = '20aa857c2b5e'
down_revision = '001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
